variables:
- name: BuildParameters.RestoreBuildProjects
  value: '**/*.csproj'
name: $(date:yyyyMMdd)$(rev:.r)
resources:
  repositories:
  - repository: self
    type: git
    ref: develop
jobs:
- job: Job_1
  displayName: Run identity tests
  pool:
    vmImage: windows-2019
  steps:
  - checkout: self
    clean: true
    submodules: recursive
    lfs: true
  - task: UseDotNet@2
    displayName: Use .NET Core sdk 3.x
    inputs:
      version: 3.x
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: $(BuildParameters.RestoreBuildProjects)
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: $(BuildParameters.RestoreBuildProjects)
      arguments: --configuration $(BuildConfiguration) --no-restore
  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish
      publishWebProjects: false
      projects: $(BuildParameters.RestoreBuildProjects)
      arguments: --configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory) --no-build
      zipAfterPublish: false
      modifyOutputPath: false
  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact
    condition: succeededOrFailed()
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'
  - task: VSTest@2
    displayName: VsTest - Run Tests
    inputs:
      testAssemblyVer2: >-
        **\Moata_Automation_Tests.dll

        !**\*TestAdapter.dll

        !**\obj\**
  - task: SpecFlowPlus@0
    displayName: SpecFlow+ build step.
    condition: succeededOrFailed()
    inputs:
      projectFilePath: Moata_Automation_Tests
      testExecutionJson: $(Build.SourcesDirectory)/Moata_Automation_Tests/bin/Release/netcoreapp3.1/TestExecution.json
      bindingAssemblies: $(Build.SourcesDirectory)/Moata_Automation_Tests/bin/Release/netcoreapp3.1/Moata_Automation_Tests.dll
...
